name: Update Jobs

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - run: pip install pandas openpyxl
      - run: python scraper.py
      - run: |
          cp jobs.json frontend/public/jobs.json
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add jobs.json frontend/public/jobs.json
          git commit -m "Automated daily job board update" || echo "No changes"
          git push
